apiVersion: apps/v1
kind: Deployment
metadata:
  name: credit-default-api
  namespace: credit-default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: credit-default-api
  template:
    metadata:
      labels:
        app: credit-default-api
    spec:
      containers:
        - name: api
          image: credit-default-api:local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
